### ISSUE TITLE
crash when i try to download an app

### ISSUE THREAD

**Issue by iacopodeenosee** [d4rken/reddit-android-appstore#124]
hi, when i try to download an app it crash, if download it via play store you should check that the intent is handled correctly and possibly show a warning.
android : lineage os 7.1.2
cell: nexus 5
this is a log:
```
08-09 11:49:36.540 23465-23472/? I/art: Debugger is no longer active
08-09 11:49:36.540 23465-23472/? I/art: Starting a blocking GC Instrumentation
08-09 11:49:36.601 23465-23465/? I/art: Starting a blocking GC AddRemoveAppImageSpace
08-09 11:49:36.688 23465-23465/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
08-09 11:49:36.799 23465-23494/? I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
08-09 11:49:36.801 23465-23494/? I/OpenGLRenderer: Initialized EGL, version 1.4
08-09 11:49:36.801 23465-23494/? D/OpenGLRenderer: Swap behavior 1
08-09 11:49:37.156 23465-23465/? W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
08-09 11:49:47.319 23465-23494/subreddit.android.appstore D/OpenGLRenderer: endAllActiveAnimators on 0x96c74480 (RippleDrawable) with handle 0x9acf0080
08-09 11:49:50.892 23465-23465/subreddit.android.appstore D/AndroidRuntime: Shutting down VM
08-09 11:49:50.893 23465-23465/subreddit.android.appstore E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: subreddit.android.appstore, PID: 23465
                                                                            android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= https://play.google.com/store/apps/details?id=au.com.codeka.advbatterygraph }
                                                                                at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1818)
                                                                                at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
                                                                                at android.app.Activity.startActivityForResult(Activity.java:4229)
                                                                                at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                                at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                                at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
                                                                                at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:146)
                                                                                at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:932)
                                                                                at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1047)
                                                                                at android.support.v4.app.Fragment.startActivity(Fragment.java:935)
                                                                                at android.support.v4.app.Fragment.startActivity(Fragment.java:924)
                                                                                at subreddit.android.appstore.screens.details.AppDetailsFragment.openDownload(AppDetailsFragment.java:186)
                                                                                at subreddit.android.appstore.screens.details.AppDetailsFragment.onDownloadClicked(AppDetailsFragment.java:163)
                                                                                at subreddit.android.appstore.screens.details.AppDetailsFragment$$ViewBinder$1.doClick(AppDetailsFragment$$ViewBinder.java:28)
                                                                                at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                                at android.view.View.performClick(View.java:5637)
                                                                                at android.view.View$PerformClick.run(View.java:22433)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

**Comment by krissrex** [comment]
Does your phone have Google Play Store installed?

**Comment by iacopodeenosee** [comment]
I installed it after; is possible add a check if the playstore is present, and if not show a warning about it, and maybe a link to download a safe apk? 
Not all have installed the playstore :)

**Comment by bobheadxi** [comment]
Similar to #74, I just added an error message to at least stop the crashing.

However, the app in question is Advanced Battery Monitor right? I get the same issue, even with the Play Store installed, seems to be an issue with the link

**Comment by krissrex** [comment]
The stack trace makes it seem like there is a space as the first character in the url: 
```
dat= https://play.google.com/store/apps/details?id=au.com.codeka.advbatterygraph
```
That could be the culprit

**Comment by bobheadxi** [comment]
Nice, I updated my PR to fix that
