### ISSUE TITLE
.screens.details.AppDetailsActivity has crash when try to send email

### ISSUE THREAD

**Issue by ITanCh** [d4rken/reddit-android-appstore#74]
```
// CRASH: subreddit.android.appstore (pid 5975)
// Short Msg: android.content.ActivityNotFoundException
// Long Msg: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SENDTO dat=mailto:xxxxxx@xxxxxxxxxxxxx.xx }
// Build Label: Android/aosp_flo/flo:6.0.1/MOB30P/tianchi10041651:userdebug/test-keys
// Build Changelist: eng.tianchi.20161004.165046
// Build Time: 1475571199000
// android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SENDTO dat=mailto:xxxxxx@xxxxxxxxxxxxx.xx }
//  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
//  at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
//  at android.app.Activity.startActivityForResult(Activity.java:3930)
//  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
//  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
//  at android.app.Activity.startActivityForResult(<Xposed>)
//  at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
//  at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
//  at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:31)
//  at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:169)
//  at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:929)
//  at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1043)
//  at android.support.v4.app.Fragment.startActivity(Fragment.java:932)
//  at android.support.v4.app.Fragment.startActivity(Fragment.java:921)
//  at subreddit.android.appstore.screens.details.AppDetailsFragment.openContact(AppDetailsFragment.java:169)
//  at subreddit.android.appstore.screens.details.AppDetailsFragment.onContactClicked(AppDetailsFragment.java:152)
//  at subreddit.android.appstore.screens.details.AppDetailsFragment.onMenuItemClick(AppDetailsFragment.java:94)
//  at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
//  at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:762)
//  at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
//  at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
//  at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
//  at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:947)
//  at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:616)
//  at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:153)
//  at android.view.View.performClick(View.java:5204)
//  at android.view.View$PerformClick.run(View.java:21153)
//  at android.os.Handler.handleCallback(Handler.java:739)
//  at android.os.Handler.dispatchMessage(Handler.java:95)
//  at android.os.Looper.loop(Looper.java:148)
//  at android.app.ActivityThread.main(ActivityThread.java:5417)
//  at java.lang.reflect.Method.invoke(Native Method)
//  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
//  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
//
```

---

When it comes to AppDetailsActivity and you click email logo that tries to send a e-mail, it will show this crash. Mybe my android os doesn't have this activity to send e-mail, but I think it should have checked if the activity SENDTO exists or catch this exception. ：）

**Comment by garretyoder** [comment]
SENDTO is a global android intent, it always exists. The android system should just display a dialog informing you that there are no available apps to handle it. What device/android version are you on?

**Comment by ITanCh** [comment]
Nexus 7 flo and  Android 6.0.1. I don't not login e-mail app in my device.

**Comment by d4rken** [comment]
Instead of crashing we can just fail gracefully and wrap it in a try/catch with a toast message.

**Comment by bobheadxi** [comment]
Fixed, https://github.com/d4rken/reddit-android-appstore/pull/93
