### ISSUE TITLE
NPE on start up

### ISSUE THREAD

**Issue by veyndan** [d4rken/reddit-android-appstore#76]
Consistently get the following exception when compiling from source.

`java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
                                                                                     at subreddit.android.appstore.backend.data.AppInfo.getPrimaryCategory(AppInfo.java:37)
                                                                                     at subreddit.android.appstore.screens.navigation.NavigationData.addApp(NavigationData.java:23)
                                                                                     at subreddit.android.appstore.screens.navigation.NavigationPresenter.lambda$onAttachView$0(NavigationPresenter.java:44)
                                                                                     at subreddit.android.appstore.screens.navigation.NavigationPresenter$$Lambda$1.apply(Unknown Source)
                                                                                     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
                                                                                     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnSubscriber.run(ObservableObserveOn.java:170)
                                                                                     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:58)
                                                                                     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)`

**Comment by veyndan** [comment]
The reason for such an error was that the subclass of `WikiRepository` that my build was using was [`FakeWikiRepository`](https://github.com/d4rken/reddit-android-appstore/blob/c69262b8b11d0ef3bcfd243f844b6d9ba9a737af/app/src/mock/java/subreddit/android/appstore/backend/reddit/wiki/FakeWikiRepository.java). As is evident from [`FakeWikiRepository#loadData`](https://github.com/d4rken/reddit-android-appstore/blob/c69262b8b11d0ef3bcfd243f844b6d9ba9a737af/app/src/mock/java/subreddit/android/appstore/backend/reddit/wiki/FakeWikiRepository.java#L29), the `AppInfo` instances never set the `categories` of `AppInfo`, therefore the above exception was raised.

The solution was to change the build variant from `mockDebug` to `prodDebug`.

**Comment by bobheadxi** [comment]
I believe I fixed the mocks and mock data in #92
