### ISSUE TITLE
Error during update check

### ISSUE THREAD

**Issue by bobheadxi** [d4rken/reddit-android-appstore#97]
Something seems to be wrong with the app update checker - error seems to point to [here](https://github.com/d4rken/reddit-android-appstore/blob/dev/app/src/main/java/subreddit/android/appstore/backend/UserAgentInterceptor.java#L37)
```
subreddit.android.appstore E/RAS:NavigationPresenter: Error during update check
                                                      java.io.InterruptedIOException: thread interrupted
                                                          at okio.Timeout.throwIfReached(Timeout.java:146)
                                                          at okio.Okio$1.write(Okio.java:75)
                                                          at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
                                                          at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
                                                          at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
                                                          at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:52)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                          at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                          at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                          at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                          at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                          at subreddit.android.appstore.backend.UserAgentInterceptor.intercept(UserAgentInterceptor.java:37)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                          at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                          at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                          at okhttp3.RealCall.execute(RealCall.java:63)
                                                          at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                          at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:41)
                                                          at io.reactivex.Observable.subscribe(Observable.java:9837)
                                                          at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
                                                          at io.reactivex.Observable.subscribe(Observable.java:9837)
                                                          at io.reactivex.internal.operators.observable.ObservableCache$CacheState.connect(ObservableCache.java:198)
                                                          at io.reactivex.internal.operators.observable.ObservableCache.subscribeActual(ObservableCache.java:84)
                                                          at io.reactivex.Observable.subscribe(Observable.java:9837)
                                                          at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
                                                          at io.reactivex.Scheduler$1.run(Scheduler.java:131)
                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:58)
                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                          at java.lang.Thread.run(Thread.java:761)
```

**Comment by bobheadxi** [comment]
Huh... can't seem to reproduce this issue anymore. Closing for now.

**Comment by d4rken** [comment]
Seems network timeout related. Does this crash the app?
It should show a small error message if this happens.

**Comment by bobheadxi** [comment]
It doesn't crash the app. Don't have much time right now but I quickly added a toast message #97 that displays when something goes wrong, if you wanted to include that for this release
